cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'caskroom/fonts'
tap 'caskroom/versions'

brew 'ack'
brew 'awscli'
brew 'coreutils'
brew 'go'
brew 'git'
brew 'git-extras'
brew 'grc'
brew 'grep'
brew 'hub'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'spark'
brew 'terraform'
brew 'trash'
brew 'unrar'
brew 'wget'
brew 'yarn', args: ['without-node']

cask 'font-source-code-pro'
cask 'font-meslo-nerd-font'

cask '1password'
cask 'alfred'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2-beta'
cask 'postman'
cask 'skitch'
cask 'slack'
cask 'spectacle'
cask 'ubersicht'
cask 'visual-studio-code'

cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
