#!/bin/sh
# Setup a machine for Sublime Text 3
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages/
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime3/User" "$sublime_dir"

# Grab the Seti UI Theme
cd "$sublime_dir"
git clone git://github.com/ctf0/Seti_ST3.git "Seti_UI"
